default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8mb4
  database: our_portfolio_production
  username: <%= ENV["OUR_PORTFOLIO_DATABASE_USER"] || "root" %>
  password: <%= ENV["OUR_PORTFOLIO_DATABASE_PASSWORD"] %>
  host: <%= ENV["OUR_PORTFOLIO_DATABASE_HOST"] || "localhost" %>
